#!/bin/python3

import math
import os
import random
import re
import sys

# Complete the miniMaxSum function below.
def miniMaxSum(arr):
    Sum = 0
    for i in range(len(arr)):
        Sum += arr[i]
    print(Sum-max(arr), Sum-min(arr))
if __name__ == '__main__':
    arr = list(map(int, input().rstrip().split()))

    miniMaxSum(arr)
